# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoChat

  target 'DemoChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DemoChat-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoChat-tvOS

end
